# Generated by Django 3.2.14 on 2022-07-15 19:51

import Profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Profiles.models.user_profile_path),
        ),
    ]
