# Generated by Django 3.2.14 on 2022-07-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
