# Generated by Django 3.2.14 on 2022-07-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_remove_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
