# Generated by Django 3.2.14 on 2022-07-21 08:11

import Profiles.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_remove_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=None, size=[510, 350], upload_to=Profiles.models.user_profile_path),
        ),
    ]
