# Generated by Django 3.2.14 on 2022-07-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_auto_20220706_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='vendor_address',
        ),
    ]
