# Generated by Django 3.2.14 on 2022-07-09 06:38

import Cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_remove_car_vendor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_length',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[Cars.models.only_digit]),
        ),
        migrations.AlterField(
            model_name='car',
            name='max_load_capacity',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[Cars.models.only_digit]),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_weight',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[Cars.models.only_digit]),
        ),
    ]
