# Generated by Django 3.2.14 on 2022-07-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0010_alter_carimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.ImageField(upload_to='cars/car_images/'),
        ),
    ]
