# Generated by Django 3.2.14 on 2022-07-21 08:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0012_alter_car_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[640, 480], upload_to='cars/car_images/'),
        ),
    ]
